version: '3.8'

services:
  transaction-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BANK_POSTGRES_HOST=postgres:5432
      - BANK_POSTGRES_DATABASE=bdb
      - BANK_POSTGRES_USERNAME=test
      - BANK_POSTGRES_PASSWORD=test
      - BANK_POSTGRES_SSLMODE=disable
      - BANK_APP_PORT=8080
      - BANK_POSTGRES_AUTOMIGRATE=true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank-network
    restart: unless-stopped

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d bdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge