# helm/transactionapi-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transactionapi-chart.fullname" . }}
  labels:
    {{- include "transactionapi-chart.labels" . | nindent 4 }}
data:
  postgres.host: {{ .Values.config.postgres.host | quote }}
  postgres.database: {{ .Values.config.postgres.database | quote }}
  postgres.userName: {{ .Values.config.postgres.userName | quote }}
  postgres.sslMode: {{ .Values.config.postgres.sslMode | quote }}
  postgres.automigrate: {{ .Values.config.postgres.automigrate | quote }}
  app.port: {{ .Values.config.app.port | quote }}
  app.environment: {{ .Values.config.app.environment | quote }}
  app.host: {{ .Values.config.app.host | quote }}