# helm/transactionapi-chart/templates/secret.yaml
{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transactionapi-chart.fullname" . }}
  labels:
    {{- include "transactionapi-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.postgresPassword }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  {{- else }}
  {{- fail "PostgreSQL password is required" }}
  {{- end }}
{{- end }}